apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  labels:
    app: api
    version: 1.0.0
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: api
